codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 3
        base: pr
      tms:
        threshold: 3
        paths:
          - tms/
          - !tms/cmd/daemons/twebd
      twebd:
        threshold: 3
        paths: "tms/cmd/daemons/twebd"
      gogroup:
        threshold: 3
        paths: "gogroup"

ignore:
  - "**/*.pb.go"
  - "**/*parser_gen.go"
  - "tms/geojson/**/*"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
