version: 0.2

env:
  variables:
    SRC_DIR: src/prisma
  parameter-store:
    CODECOV_TOKEN: PRISMA_CODECOV_ACCOUNT_TOKEN
phases:
  pre_build:
    commands:
      - export GOPATH=/root/go
      - mkdir -p ${GOPATH}/${SRC_DIR} && cd ${GOPATH}/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${CODEBUILD_SRC_DIR}/.??* .
      - env
      - go env
      - go version
      - cat /etc/lsb-release
      - service rsyslog start
  build:
    commands:
      - echo Build started on `date`
      - cd ${GOPATH}/${SRC_DIR}
      - make mod
      - make protobuf
      - make version
      - make compile
      - make lint
      - make cover
  post_build:
    commands:
      - export VCS_COMMIT_ID="$(git rev-parse HEAD)"
      - echo "#!/bin/bash\nbash <(curl -s https://codecov.io/bash) -B ${CODEBUILD_BUILD_ID} -X detect -c $VCS_COMMIT_ID" > codecov.sh; chmod +x codecov.sh; ./codecov.sh
      - echo Build completed on `date`
