version: 0.2

env:
  variables:
    SRC_DIR: src/prisma
  parameter-store:
    CODECOV_TOKEN: PRISMA_CODECOV_ACCOUNT_TOKEN
phases:
  pre_build:
    commands:
      - export GOPATH=/root/go
      - export DOCUMENTATION_FOLDER=$([ $CODEBUILD_WEBHOOK_HEAD_REF = 'refs/heads/master' ] && echo "latest" || echo "nightly")
      - mkdir -p ${GOPATH}/${SRC_DIR} && cd ${GOPATH}/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${CODEBUILD_SRC_DIR}/.??* .
      - env
      - go env
      - go version
      - service rsyslog start
  build:
    commands:
      - echo Build started on `date`
      - cd ${GOPATH}/${SRC_DIR}
      - make mod
      - make protobuf
      - make version
      - make compile
      - make/deb-release
      - make lint
      - make cover
      - make docs
      - make godoc
  post_build:
    commands:
      - echo Deploying documentation site
      - cd ${GOPATH}/${SRC_DIR}/build/documentation_site
      - aws s3 sync . s3://prisma-documentation/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - echo Deploying godoc site
      - cd ${GOPATH}/${SRC_DIR}/build/godoc
      - aws s3 sync . s3://prisma-documentation/godoc/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - aws cloudfront create-invalidation --distribution-id=e3hjfq1l5x1noh --paths '/nightly/*' '/godoc/nightly/*' '/latest/*' '/godoc/latest/*'
      - echo Uploading coverage
      - export VCS_COMMIT_ID="$(git rev-parse HEAD)"
      - echo "#!/bin/bash\nbash <(curl -s https://codecov.io/bash) -B ${CODEBUILD_BUILD_ID} -X detect -c $VCS_COMMIT_ID" > codecov.sh; chmod +x codecov.sh; ./codecov.sh
      - echo Build completed on `date`

artifacts:
  files:
    - dist/*.deb
  base-directory: ${GOPATH}/${SRC_DIR}
  name: prisma-${VERSION}
