version: 0.2

env:
  variables:
    SRC_DIR: src/prisma
phases:
  pre_build:
    commands:
      - export GOPATH=/root/go
      - export FILE_VERSION=$(cat ./VERSION.txt)
      - export TAG_VERSION=git tag --points-at HEAD | tr -d v
      - export VERSION=$([ ! -z $TAG_VERSION ] && echo $TAG_VERSION || echo $FILE_VERSION)
      - mkdir -p ${GOPATH}/${SRC_DIR} && cd ${GOPATH}/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${CODEBUILD_SRC_DIR}/.??* .
      - echo "Copying dependency debians to repository..."
      - mkdir -p /usr/local/prisma-repository/
      - aws s3 sync s3://prisma-c2/dependencies/all-dependencies/ /usr/local/prisma-repository/ --quiet
      - service rsyslog start
      - env
      - go env
      - go version
  build:
    commands:
      - echo Build started on `date`
      - echo Current VERSION ${VERSION}
      - cd ${GOPATH}/${SRC_DIR}
      - make mod
      - make protobuf
      - make version
      - make compile
      - make/deb-release
      - make lint
      - make cover
      - make docs
      - make godoc
  post_build:
    commands:
      - echo Deploying documentation site
      - cd ${GOPATH}/${SRC_DIR}/build/documentation_site
      - aws s3 sync . s3://prisma-documentation/${VERSION}/ --delete --quiet
      - echo Deploying godoc site
      - cd ${GOPATH}/${SRC_DIR}/build/godoc
      - aws s3 sync . s3://prisma-documentation/godoc/${VERSION}/ --delete --quiet
      - echo Packaging installer
      - cd ${GOPATH}/${SRC_DIR}/make/installer
      - cp ../../dist/*.deb /usr/local/prisma-repository/
      - sh ./package-prisma-repository ${VERSION}
      - cd ${GOPATH}/${SRC_DIR}
      - mv make/installer/dist/PRISMA_Server_Install-${VERSION} ./
      - aws cloudfront create-invalidation --distribution-id=e3hjfq1l5x1noh --paths "/${VERSION}/*" "/godoc/${VERSION}/*"
      - echo Build completed on `date`

artifacts:
  files:
    - dist/*.deb
    - PRISMA_Server_Install-${VERSION}
  base-directory: ${GOPATH}/${SRC_DIR}
  name: ${VERSION}
