auth = 'https://localhost:8181/api/v2/auth'
tauthd = 'https://localhost:8181/api/v2/auth/apidocs.json'
tms = 'https://localhost:8080/api/v2'
twebd = 'https://localhost:8080/api/v2/apidocs.json'
simulator = 'http://localhost:8089/v1'
config = 'http://localhost:8081/api/v2/config.json'
json = {'Content-Type': 'application/json'}
websocket_base = 'wss://localhost:8080/ws/v2'
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DB_AAA = 'aaa'
MONGO_DB_TRIDENT = 'trident'
