version: 0.0

os: linux

files:
  - source: /
    destination: /opt/go/src/prisma/
    overwrite: true

permissions:
  - object: /opt/go/src/
    owner: ec2-user
    mode: 777
    type:
      - directory

hooks:
  AfterInstall:
    - location: etc/aws/scripts/sonarqube-scanner-client.sh
      timeout: 3600
      runas: ec2-user
