//Test Mode Ack(0x30), Iridium/3G
// Code generated by omnicom; DO NOT EDIT
package omnicom

import (
	"errors"
	"strconv"
)

type TMA struct {
	Header  byte
	Date    Date
	Padding uint32
	CRC     uint32
}

func (TMA *TMA) Parse(input string) error {
	var err error
	if len(input) > 48 {
		err = errors.New("Input message is longer than limit")
		return err
	}
	var count int = 0
	if count+8 > len(input) {
		err = errors.New("Input message length of TMA is shorter than required")
		return err
	}
	count = count + 8
	if count+27 > len(input) {
		err = errors.New("Input message length of TMA is shorter than required")
		return err
	}
	TMA.Date = *new(Date)
	err = TMA.Date.parse(input[count : count+27])
	count = count + 27
	if err != nil {
		return err
	}
	var num uint64
	if count+(8-count%8) > len(input) {
		err = errors.New("Input message length of TMA is shorter than required")
		return err
	}
	num, err = strconv.ParseUint(input[count:count+(8-count%8)], 2, 32)
	TMA.Padding = uint32(num*1 - 0)
	count = count + (8 - count%8)
	if err != nil {
		return err
	}
	if count+8 > len(input) {
		err = errors.New("Input message length of TMA is shorter than required")
		return err
	}
	num, err = strconv.ParseUint(input[count:count+8], 2, 32)
	TMA.CRC = uint32(num*1 - 0)
	count = count + 8
	if err != nil {
		return err
	}
	return err
}
func (TMA *TMA) Encode() ([]byte, error) {
	var str string
	var s string
	var err error
	str += pad(strconv.FormatUint(uint64(TMA.Header), 2), 8)
	s, err = TMA.Date.encode()
	if err != nil {
		return []byte{}, err
	}
	str += s

	s = pad(strconv.FormatUint(uint64((TMA.Padding+0)/1), 2), 8-len(str)%8)
	if len(s) > (8 - len(str)%8) {
		err = errors.New("Value assigned for TMA.Padding exceeds limit")
		return []byte{}, err
	}
	str += s

	s = pad(strconv.FormatUint(uint64((TMA.CRC+0)/1), 2), 8)
	if len(s) > 8 {
		err = errors.New("Value assigned for TMA.CRC exceeds limit")
		return []byte{}, err
	}
	str += s

	str = attachCRC(str)
	byteList, err := decToByte(str)
	return byteList, err
}
func (TMA *TMA) getHeader() byte {
	return TMA.Header
}
func (TMA *TMA) getCRC() uint32 {
	return TMA.CRC
}
func (TMA *TMA) setCRC(crc uint32) {
	TMA.CRC = crc
}
