//UpdateAPI url parameters(0x3A), Iridium/3G
// Code generated by omnicom; DO NOT EDIT
package omnicom

import (
	"errors"
	"strconv"
)

type UAUP struct {
	Header                        byte
	ID_Msg                        uint32
	Date                          Date
	Web_Service_API_URL_Sending   Web_Service_API_URL_sending_StoV
	Web_Service_API_URL_Receiving Web_Service_API_URL_Receiving_StoV
	Array                         Array_StoV
	Padding                       uint32
	CRC                           uint32
}

func (UAUP *UAUP) Parse(input string) error {
	var err error
	if len(input) > 1392 {
		err = errors.New("Input message is longer than limit")
		return err
	}
	var count int = 0
	if count+8 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	count = count + 8
	var num uint64
	if count+12 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	num, err = strconv.ParseUint(input[count:count+12], 2, 32)
	UAUP.ID_Msg = uint32(num*1 - 0)
	count = count + 12
	if err != nil {
		return err
	}
	if count+27 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	UAUP.Date = *new(Date)
	err = UAUP.Date.parse(input[count : count+27])
	count = count + 27
	if err != nil {
		return err
	}
	if count+601 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	UAUP.Web_Service_API_URL_Sending = *new(Web_Service_API_URL_sending_StoV)
	err = UAUP.Web_Service_API_URL_Sending.parse(input[count : count+601])
	count = count + 601
	if err != nil {
		return err
	}
	if count+601 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	UAUP.Web_Service_API_URL_Receiving = *new(Web_Service_API_URL_Receiving_StoV)
	err = UAUP.Web_Service_API_URL_Receiving.parse(input[count : count+601])
	count = count + 601
	if err != nil {
		return err
	}
	if count+129 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	UAUP.Array = *new(Array_StoV)
	err = UAUP.Array.parse(input[count : count+129])
	count = count + 129
	if err != nil {
		return err
	}
	if count+(8-count%8) > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	num, err = strconv.ParseUint(input[count:count+(8-count%8)], 2, 32)
	UAUP.Padding = uint32(num*1 - 0)
	count = count + (8 - count%8)
	if err != nil {
		return err
	}
	if count+8 > len(input) {
		err = errors.New("Input message length of UAUP is shorter than required")
		return err
	}
	num, err = strconv.ParseUint(input[count:count+8], 2, 32)
	UAUP.CRC = uint32(num*1 - 0)
	count = count + 8
	if err != nil {
		return err
	}
	return err
}
func (UAUP *UAUP) Encode() ([]byte, error) {
	var str string
	var s string
	var err error
	str += pad(strconv.FormatUint(uint64(UAUP.Header), 2), 8)
	s = pad(strconv.FormatUint(uint64((UAUP.ID_Msg+0)/1), 2), 12)
	if len(s) > 12 {
		err = errors.New("Value assigned for UAUP.ID_Msg exceeds limit")
		return []byte{}, err
	}
	str += s

	s, err = UAUP.Date.encode()
	if err != nil {
		return []byte{}, err
	}
	str += s

	s, err = UAUP.Web_Service_API_URL_Sending.encode()
	if err != nil {
		return []byte{}, err
	}
	str += s

	s, err = UAUP.Web_Service_API_URL_Receiving.encode()
	if err != nil {
		return []byte{}, err
	}
	str += s

	s, err = UAUP.Array.encode()
	if err != nil {
		return []byte{}, err
	}
	str += s

	s = pad(strconv.FormatUint(uint64((UAUP.Padding+0)/1), 2), 8-len(str)%8)
	if len(s) > (8 - len(str)%8) {
		err = errors.New("Value assigned for UAUP.Padding exceeds limit")
		return []byte{}, err
	}
	str += s

	s = pad(strconv.FormatUint(uint64((UAUP.CRC+0)/1), 2), 8)
	if len(s) > 8 {
		err = errors.New("Value assigned for UAUP.CRC exceeds limit")
		return []byte{}, err
	}
	str += s

	str = attachCRC(str)
	byteList, err := decToByte(str)
	return byteList, err
}
func (UAUP *UAUP) getHeader() byte {
	return UAUP.Header
}
func (UAUP *UAUP) getCRC() uint32 {
	return UAUP.CRC
}
func (UAUP *UAUP) setCRC(crc uint32) {
	UAUP.CRC = crc
}
