// Code generated by parse_nmea; DO NOT EDIT
package nmea

import "fmt"
import "strconv"
import "strings"

// M137124B represents fix data.
type CoreM137124B struct {
	MessageID uint8

	RepeatIndicator uint32

	Mmsi uint32

	PartNumber uint32

	ShipAndCargoType uint32

	VendorID string

	CallSign string

	DimBow uint32

	DimStern uint32

	DimPort uint32

	DimStarboard uint32

	Spare uint32 //Supposed to be Unknown
}
type M137124B struct {
	VDMO
	CoreM137124B
}

func NewM137124B(sentence VDMO) *M137124B {
	s := new(M137124B)
	s.VDMO = sentence
	return s
}

func (s *M137124B) parse() error {
	var err error

	if MessageType(s.EncapData) != 24 {
		err = fmt.Errorf("message %d is not a M137124B", MessageType(s.EncapData))
		return err
	}

	data := []byte(s.EncapData)

	//if len(data)*6 > 168 {
	//	err = fmt.Errorf("Message lenght is larger than it should be [%d!=168]", len(data)*6)
	//	return err
	//}

	s.MessageID = MessageType(s.EncapData)

	s.CoreM137124B.RepeatIndicator = BitsToInt(6, 7, data)

	s.CoreM137124B.Mmsi = BitsToInt(8, 37, data)

	s.CoreM137124B.PartNumber = BitsToInt(38, 39, data)

	s.CoreM137124B.ShipAndCargoType = BitsToInt(40, 47, data)

	s.CoreM137124B.VendorID = BitsToString(48, 89, data)

	s.CoreM137124B.CallSign = BitsToString(90, 131, data)

	s.CoreM137124B.DimBow = BitsToInt(132, 140, data)

	s.CoreM137124B.DimStern = BitsToInt(141, 149, data)

	s.CoreM137124B.DimPort = BitsToInt(150, 155, data)

	s.CoreM137124B.DimStarboard = BitsToInt(156, 161, data)

	s.CoreM137124B.Spare = BitsToInt(162, 6*(len(data)-1), data)

	return nil
}

func (s *M137124B) Encode() (string, error) {
	var Raw string
	var Sbinary string

	if s.MessageID != 24 {
		err := fmt.Errorf("message %d is not a M137124B", s.MessageID)
		return "", err
	}

	Raw = s.SOS + s.Talker + s.Format + ","

	if s.SentenceCountValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceCount), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SentenceIndexValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceIndex), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SeqMsgIDValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SeqMsgID), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.ChannelValidity == true {
		Raw = Raw + s.Channel
	}

	str := strconv.FormatInt(int64(s.CoreM137124B.MessageID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.RepeatIndicator), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.Mmsi), 2)
	for len(str) < 30 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.PartNumber), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.ShipAndCargoType), 2)
	for len(str) < 8 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	if s.CoreM137124B.VendorID != "" {
		str = ""

		for len([]byte(s.CoreM137124B.VendorID)) < 42/6 {
			s.CoreM137124B.VendorID = s.CoreM137124B.VendorID + "@"

		}

		for _, n := range []byte(s.CoreM137124B.VendorID) {
			if n >= 32 {
				n = n - 64
			}
			name := strconv.FormatInt(int64(n), 2)
			for len(name) < 6 {
				name = "0" + name
			}

			if len(name) > 6 {
				if len(name) == 8 {
					n = n - 128
					name = strconv.FormatInt(int64(n), 2)
				}
				if len(name) == 7 {
					n = n - 64
					name = strconv.FormatInt(int64(n), 2)
				}
			}

			str = str + name

		}

		Sbinary = Sbinary + str

	}

	if s.CoreM137124B.CallSign != "" {
		str = ""

		for len([]byte(s.CoreM137124B.CallSign)) < 42/6 {
			s.CoreM137124B.CallSign = s.CoreM137124B.CallSign + "@"

		}

		for _, n := range []byte(s.CoreM137124B.CallSign) {
			if n >= 32 {
				n = n - 64
			}
			name := strconv.FormatInt(int64(n), 2)
			for len(name) < 6 {
				name = "0" + name
			}

			if len(name) > 6 {
				if len(name) == 8 {
					n = n - 128
					name = strconv.FormatInt(int64(n), 2)
				}
				if len(name) == 7 {
					n = n - 64
					name = strconv.FormatInt(int64(n), 2)
				}
			}

			str = str + name

		}

		Sbinary = Sbinary + str

	}

	str = strconv.FormatInt(int64(s.CoreM137124B.DimBow), 2)
	for len(str) < 9 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.DimStern), 2)
	for len(str) < 9 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.DimPort), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.DimStarboard), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137124B.Spare), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	field := strings.SplitN(Sbinary, "", len(Sbinary))

	var encdata = make([]string, int((len(Sbinary)+int(s.FillBits))/6))

	j := 0
	for i := 0; i < int((len(Sbinary)+int(s.FillBits))/6); i++ {

		if i == (int((len(Sbinary)+int(s.FillBits))/6) - 1) {
			for j < len(Sbinary) {
				encdata[i] = encdata[i] + field[j]
				j = j + 1
			}
			for h := 0; h < int(s.FillBits); h++ {
				encdata[i] = encdata[i] + "0" // fill bits
			}
		} else {
			encdata[i] = field[j] + field[j+1] + field[j+2] + field[j+3] + field[j+4] + field[j+5]
			j = j + 6
		}
	}

	var data string
	for j := 0; j < int((len(Sbinary)+int(s.FillBits))/6); j++ {
		i, _ := strconv.ParseInt(encdata[j], 2, 8)
		if i < 40 {
			i = i + 48
		} else {
			i = i + 8 + 48
		}
		data = data + string(rune(i))
	}

	Raw = Raw + "," + data + ","

	if s.FillBitsValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.FillBits), 10)
	}

	check := Checksum(Raw)

	Raw = Raw + check

	return Raw, nil

}
