// Code generated by parse_nmea; DO NOT EDIT
package nmea

import "fmt"
import "strconv"
import "strings"

// M137115 represents fix data.
type CoreM137115 struct {
	MessageID uint8

	RepeatIndicator uint32

	Mmsi uint32

	Spare1 uint32 //Supposed to be Unknown

	Destination1ID uint32

	Message11ID uint32

	SlotOffset11 uint32

	Spare2 uint32 //Supposed to be Unknown

	Message12ID uint32

	SlotOffset12 uint32

	Spare3 uint32 //Supposed to be Unknown

	Destination2ID uint32

	Message21ID uint32

	SlotOffset21 uint32

	Spare4 uint32 //Supposed to be Unknown
}
type M137115 struct {
	VDMO
	CoreM137115
}

func NewM137115(sentence VDMO) *M137115 {
	s := new(M137115)
	s.VDMO = sentence
	return s
}

func (s *M137115) parse() error {
	var err error

	if MessageType(s.EncapData) != 15 {
		err = fmt.Errorf("message %d is not a M137115", MessageType(s.EncapData))
		return err
	}

	data := []byte(s.EncapData)

	//if len(data)*6 > 160 {
	//	err = fmt.Errorf("Message lenght is larger than it should be [%d!=160]", len(data)*6)
	//	return err
	//}

	s.MessageID = MessageType(s.EncapData)

	s.CoreM137115.RepeatIndicator = BitsToInt(6, 7, data)

	s.CoreM137115.Mmsi = BitsToInt(8, 37, data)

	s.CoreM137115.Spare1 = BitsToInt(38, 39, data)

	s.CoreM137115.Destination1ID = BitsToInt(40, 69, data)

	s.CoreM137115.Message11ID = BitsToInt(70, 75, data)

	s.CoreM137115.SlotOffset11 = BitsToInt(76, 87, data)

	s.CoreM137115.Spare2 = BitsToInt(88, 89, data)

	s.CoreM137115.Message12ID = BitsToInt(90, 95, data)

	s.CoreM137115.SlotOffset12 = BitsToInt(96, 107, data)

	s.CoreM137115.Spare3 = BitsToInt(108, 109, data)

	s.CoreM137115.Destination2ID = BitsToInt(110, 139, data)

	s.CoreM137115.Message21ID = BitsToInt(140, 145, data)

	s.CoreM137115.SlotOffset21 = BitsToInt(146, 157, data)

	s.CoreM137115.Spare4 = BitsToInt(158, 6*(len(data)-1), data)

	return nil
}

func (s *M137115) Encode() (string, error) {
	var Raw string
	var Sbinary string

	if s.MessageID != 15 {
		err := fmt.Errorf("message %d is not a M137115", s.MessageID)
		return "", err
	}

	Raw = s.SOS + s.Talker + s.Format + ","

	if s.SentenceCountValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceCount), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SentenceIndexValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceIndex), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SeqMsgIDValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SeqMsgID), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.ChannelValidity == true {
		Raw = Raw + s.Channel
	}

	str := strconv.FormatInt(int64(s.CoreM137115.MessageID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.RepeatIndicator), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Mmsi), 2)
	for len(str) < 30 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Spare1), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Destination1ID), 2)
	for len(str) < 30 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Message11ID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.SlotOffset11), 2)
	for len(str) < 12 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Spare2), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Message12ID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.SlotOffset12), 2)
	for len(str) < 12 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Spare3), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Destination2ID), 2)
	for len(str) < 30 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Message21ID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.SlotOffset21), 2)
	for len(str) < 12 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137115.Spare4), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	field := strings.SplitN(Sbinary, "", len(Sbinary))

	var encdata = make([]string, int((len(Sbinary)+int(s.FillBits))/6))

	j := 0
	for i := 0; i < int((len(Sbinary)+int(s.FillBits))/6); i++ {

		if i == (int((len(Sbinary)+int(s.FillBits))/6) - 1) {
			for j < len(Sbinary) {
				encdata[i] = encdata[i] + field[j]
				j = j + 1
			}
			for h := 0; h < int(s.FillBits); h++ {
				encdata[i] = encdata[i] + "0" // fill bits
			}
		} else {
			encdata[i] = field[j] + field[j+1] + field[j+2] + field[j+3] + field[j+4] + field[j+5]
			j = j + 6
		}
	}

	var data string
	for j := 0; j < int((len(Sbinary)+int(s.FillBits))/6); j++ {
		i, _ := strconv.ParseInt(encdata[j], 2, 8)
		if i < 40 {
			i = i + 48
		} else {
			i = i + 8 + 48
		}
		data = data + string(rune(i))
	}

	Raw = Raw + "," + data + ","

	if s.FillBitsValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.FillBits), 10)
	}

	check := Checksum(Raw)

	Raw = Raw + check

	return Raw, nil

}
