// Code generated by parse_nmea; DO NOT EDIT
package nmea

import "fmt"
import "strconv"
import "strings"

// M137111 represents fix data.
type CoreM137111 struct {
	MessageID uint8

	RepeatIndicator uint32

	Mmsi uint32

	UtcYear uint32

	UtcMonth uint32

	UtcDay uint32

	UtcHour uint32

	UtcMinute uint32

	UtcSecond uint32

	PositionAccuracy bool

	Longitude float64

	Latitude float64

	PositionDevice uint32

	Spare uint32 //Supposed to be Unknown

	RaimFlag bool

	CommState uint32 //Supposed to be Unknown
}
type M137111 struct {
	VDMO
	CoreM137111
}

func NewM137111(sentence VDMO) *M137111 {
	s := new(M137111)
	s.VDMO = sentence
	return s
}

func (s *M137111) parse() error {
	var err error

	if MessageType(s.EncapData) != 11 {
		err = fmt.Errorf("message %d is not a M137111", MessageType(s.EncapData))
		return err
	}

	data := []byte(s.EncapData)

	//if len(data)*6 > 168 {
	//	err = fmt.Errorf("Message lenght is larger than it should be [%d!=168]", len(data)*6)
	//	return err
	//}

	s.MessageID = MessageType(s.EncapData)

	s.CoreM137111.RepeatIndicator = BitsToInt(6, 7, data)

	s.CoreM137111.Mmsi = BitsToInt(8, 37, data)

	s.CoreM137111.UtcYear = BitsToInt(38, 51, data)

	s.CoreM137111.UtcMonth = BitsToInt(52, 55, data)

	s.CoreM137111.UtcDay = BitsToInt(56, 60, data)

	s.CoreM137111.UtcHour = BitsToInt(61, 65, data)

	s.CoreM137111.UtcMinute = BitsToInt(66, 71, data)

	s.CoreM137111.UtcSecond = BitsToInt(72, 77, data)

	s.CoreM137111.PositionAccuracy = CbnBool(78, data)

	s.CoreM137111.Longitude = (float64(int32(BitsToInt(79, 106, data)) << 4)) / 16

	s.CoreM137111.Latitude = (float64(int32(BitsToInt(107, 133, data)) << 5)) / 32

	s.CoreM137111.PositionDevice = BitsToInt(134, 137, data)

	s.CoreM137111.Spare = BitsToInt(138, 147, data)

	s.CoreM137111.RaimFlag = CbnBool(148, data)

	s.CoreM137111.CommState = BitsToInt(149, 6*(len(data)-1), data)

	return nil
}

func (s *M137111) Encode() (string, error) {
	var Raw string
	var Sbinary string

	if s.MessageID != 11 {
		err := fmt.Errorf("message %d is not a M137111", s.MessageID)
		return "", err
	}

	Raw = s.SOS + s.Talker + s.Format + ","

	if s.SentenceCountValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceCount), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SentenceIndexValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SentenceIndex), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.SeqMsgIDValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.SeqMsgID), 10) + ","
	} else {
		Raw = Raw + ","
	}

	if s.ChannelValidity == true {
		Raw = Raw + s.Channel
	}

	str := strconv.FormatInt(int64(s.CoreM137111.MessageID), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.RepeatIndicator), 2)
	for len(str) < 2 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.Mmsi), 2)
	for len(str) < 30 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcYear), 2)
	for len(str) < 14 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcMonth), 2)
	for len(str) < 4 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcDay), 2)
	for len(str) < 5 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcHour), 2)
	for len(str) < 5 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcMinute), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.UtcSecond), 2)
	for len(str) < 6 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	if s.PositionAccuracy == true {
		str = "1"
	} else {
		str = "0"
	}

	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.Longitude), 2)
	for len(str) < 28 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.Latitude), 2)
	for len(str) < 27 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.PositionDevice), 2)
	for len(str) < 4 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.Spare), 2)
	for len(str) < 10 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	if s.RaimFlag == true {
		str = "1"
	} else {
		str = "0"
	}

	Sbinary = Sbinary + str

	str = strconv.FormatInt(int64(s.CoreM137111.CommState), 2)
	for len(str) < 19 {
		str = "0" + str
	}
	Sbinary = Sbinary + str

	field := strings.SplitN(Sbinary, "", len(Sbinary))

	var encdata = make([]string, int((len(Sbinary)+int(s.FillBits))/6))

	j := 0
	for i := 0; i < int((len(Sbinary)+int(s.FillBits))/6); i++ {

		if i == (int((len(Sbinary)+int(s.FillBits))/6) - 1) {
			for j < len(Sbinary) {
				encdata[i] = encdata[i] + field[j]
				j = j + 1
			}
			for h := 0; h < int(s.FillBits); h++ {
				encdata[i] = encdata[i] + "0" // fill bits
			}
		} else {
			encdata[i] = field[j] + field[j+1] + field[j+2] + field[j+3] + field[j+4] + field[j+5]
			j = j + 6
		}
	}

	var data string
	for j := 0; j < int((len(Sbinary)+int(s.FillBits))/6); j++ {
		i, _ := strconv.ParseInt(encdata[j], 2, 8)
		if i < 40 {
			i = i + 48
		} else {
			i = i + 8 + 48
		}
		data = data + string(rune(i))
	}

	Raw = Raw + "," + data + ","

	if s.FillBitsValidity == true {
		Raw = Raw + strconv.FormatInt(int64(s.FillBits), 10)
	}

	check := Checksum(Raw)

	Raw = Raw + check

	return Raw, nil

}
